services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: start.sh jupyter lab --LabApp.token='password' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
    networks:
      - net

networks:
  net:
    driver: bridge